version: '3.8'

services:
  # RabbitMQ сервис
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"  # для связи с приложениями
      - "15672:15672"  # для веб-менеджера RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  # Person Service
  person_service:
    build:
      context: ./person_service  # Указываем путь к директории person_service
    container_name: person_service
    ports:
      - "8001:8000"  # Пробрасываем порт 8000 для взаимодействия с приложением
    depends_on:
      - rabbitmq  # Указываем зависимость от RabbitMQ
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest

  # Project Service
  project_service:
    build:
      context: ./project_service  # Указываем путь к директории project_service
    container_name: project_service
    ports:
      - "8002:8000"  # Пробрасываем порт 8001 для взаимодействия с приложением
    depends_on:
      - rabbitmq  # Указываем зависимость от RabbitMQ
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest

  # Project Access Service
  project_access_service:
    build:
      context: ./project_access_service  # Указываем путь к директории project_access_service
    container_name: project_access_service
    ports:
      - "8003:8000"  # Пробрасываем порт 8002 для взаимодействия с приложением
    depends_on:
      - rabbitmq  # Указываем зависимость от RabbitMQ
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest

# Определяем том для хранения данных RabbitMQ
volumes:
  rabbitmq-data:
